public class TaskListPojo {
    
     public Id id;
     public String picklistValue;
     public String aPIFieldName;
     public String validaytionOnText;
     public String name;
     public Boolean isCompleted;
     public Boolean isEditable;
     public Boolean isResponseMnadetory;
     public String mVProcess;
     public String taskResponse;
     public String tasktype;
     public String taskText;
     public DateTime CreatedDate;
     public Decimal position;
     public String locationLevel;
     public String isHeader;
    
    public String lanTsaskText;
    public String lanPicklistValue;
    public void tesMethod1()
    {
        Integer i =0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
    
}