public class WS_CallgetallprocessandtaskNew {
    public static List<WS_getallprocessandtaskNew.TaskAndProcessResponse> callWebService(String userId,String lan)
        {
            			List<WS_getallprocessandtaskNew.TaskAndProcessResponse> l = new List<WS_getallprocessandtaskNew.TaskAndProcessResponse>();

          /*
			WS_getallprocessandtaskNew.userId = userId;
			WS_getallprocessandtaskNew.lan = lan;
			List<WS_getallprocessandtaskNew.TaskAndProcessResponse> l = new List<WS_getallprocessandtaskNew.TaskAndProcessResponse>();
			l = WS_getallprocessandtaskNew.doGet();

			for(WS_getallprocessandtaskNew.TaskAndProcessResponse r: l)
				{
    				System.debug('Output is'+ r.prc.Name);
				}*/
            return l;
        }
    
     public static void  CCHelp()
    {
       Integer val = 1;
       
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
    }

}