@RestResource(urlMapping='/getOrganization/*')
global with sharing class WS_getOrganization {

    @HttpGet
    global static List<String> doGet() {
        Schema.DescribeFieldResult fieldResult = MV_Role__c.Organisation__c.getDescribe();
   List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    List<String> options = new List<String>();
    
   for( Schema.PicklistEntry f : ple){  
       options.add(f.getValue());
    }       
        return options;
    }
    public static void  CCHelp()
    {
       Integer val = 1;
       
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
        val=val+1;
       
        }  
}